//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioPracticoBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ajuste
    {
        public int AjusteId { get; set; }
        public int ClienteId { get; set; }
        public decimal MontoTotal { get; set; }
        public decimal Adedudo { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
